defmodule Moorland.Storage do
  @moduledoc """
  Where the user's writing lives - and the guarantee that it stays theirs.

  The data folder holds the SQLite database plus a `scripts/` folder carrying
  a plain-text `.fountain` mirror of every script, refreshed on every save.
  Fountain is an open plain-text format, so the mirror is readable and
  recoverable with nothing but a text editor - no Moorland required. The
  folder can live anywhere: another drive, or a Google Drive / iCloud /
  Dropbox folder for automatic cloud backup.
  """

  require Logger

  alias Moorland.Repo
  alias Moorland.Scripts.Script

  def database_path, do: to_string(Repo.config()[:database])
  def data_dir, do: Path.dirname(database_path())

  def mirror_dir do
    Application.get_env(:moorland, :mirror_dir) || Path.join(data_dir(), "scripts")
  end

  def pointer_path do
    Application.get_env(:moorland, :data_dir_pointer) ||
      Path.join(System.user_home!(), ".moorland/data_dir")
  end

  def mirroring?, do: Application.get_env(:moorland, :mirror_scripts, true)

  @doc "Writes/refreshes the script's plain-text .fountain mirror. Never raises."
  def mirror_script(%Script{} = script) do
    if mirroring?() do
      try do
        dir = mirror_dir()
        File.mkdir_p!(dir)
        remove_stale(dir, script.id)
        File.write!(Path.join(dir, filename(script)), script.content || "")
      rescue
        error -> Logger.warning("script mirror failed: #{Exception.message(error)}")
      end
    end

    :ok
  end

  def remove_mirror(%Script{} = script) do
    if mirroring?() do
      try do
        remove_stale(mirror_dir(), script.id)
      rescue
        error -> Logger.warning("mirror removal failed: #{Exception.message(error)}")
      end
    end

    :ok
  end

  @doc "Backfills mirrors for every script (run once at boot)."
  def mirror_all do
    if mirroring?() do
      Repo.all(Script) |> Enum.each(&mirror_script/1)
    end

    :ok
  end

  @doc """
  Points Moorland's data folder somewhere new. A folder already holding a
  moorland.db is adopted as-is; otherwise the current database is
  checkpointed and copied in. Takes effect on the next start; the .fountain
  mirrors regenerate there automatically.
  """
  def relocate(new_dir) do
    new_dir = Path.expand(String.trim(to_string(new_dir)))
    target = Path.join(new_dir, "moorland.db")

    with :ok <- File.mkdir_p(new_dir),
         :ok <- writable_check(new_dir) do
      mode =
        if File.exists?(target) do
          :adopted
        else
          # Fold the write-ahead log into the main file when possible; either
          # way the -wal/-shm companions are copied too, so nothing is lost.
          try do
            Repo.query!("PRAGMA wal_checkpoint(TRUNCATE)")
          rescue
            _ -> :ok
          end

          File.cp!(database_path(), target)

          # Best-effort: -shm is regenerated by SQLite and is often locked on
          # Windows; -wal only matters when the checkpoint above was skipped.
          for suffix <- ["-wal", "-shm"],
              source = database_path() <> suffix,
              File.exists?(source) do
            File.cp(source, target <> suffix)
          end

          :copied
        end

      pointer = pointer_path()
      File.mkdir_p!(Path.dirname(pointer))
      File.write!(pointer, new_dir)
      {:ok, mode, new_dir}
    else
      {:error, reason} -> {:error, "#{inspect(reason)}"}
    end
  rescue
    error -> {:error, Exception.message(error)}
  end

  defp writable_check(dir) do
    probe = Path.join(dir, ".moorland-write-test")

    case File.write(probe, "ok") do
      :ok ->
        File.rm(probe)
        :ok

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp filename(%Script{} = script) do
    slug =
      script.title
      |> to_string()
      |> String.replace(~r/[\\\/:*?"<>|]/, "")
      |> String.trim()
      |> String.slice(0, 80)

    slug = if slug == "", do: "untitled", else: slug
    "#{slug} (#{script.id}).fountain"
  end

  defp remove_stale(dir, id) do
    # Wildcard patterns treat backslashes as escapes; normalize for Windows.
    dir
    |> Path.join("* (#{id}).fountain")
    |> String.replace("\\", "/")
    |> Path.wildcard()
    |> Enum.each(&File.rm/1)
  end
end
